### ISSUE TITLE
banregiolabs

### ISSUE THREAD

**Issue by jasbu** [edmt/guia_para_colaborar#1]
Hola Daniel! Disculpa te contacte por aquí pero quiero ayuda con el API de banregio y no he tenido suerte contactandome a los correos y numeros registrados. Está abandonado el proyecto? O como lo puedo usar? En particular, quería bajarme el SDK para python.

Saludos

**Comment by edmt** [comment]
@jasbu Hola, no hay problema en que me contactes por aquí.

Lo que sucede es que el API de Banregio ya no va a ser mantenido, así que el proyecto sí está un tanto abandonado. En un futuro será reemplazado por un API basada en la especificación de Open Banking, pero lamentablemente no tengo más detalles.

Saludos.

**Comment by jasbu** [comment]
:( Muchas gracias, espero no tarden mucho con la nueva versión
